### ISSUE TITLE
With WITH_SDFTD3=ON configure finds the external package toml-f package but built binaries aren't linked with libtoml-f.so

### ISSUE THREAD

**Issue by yurivict** [dftbplus/dftbplus#1040]
Version 22.1

**Comment by awvwgk** [comment]
See

https://github.com/dftd3/simple-dftd3/blob/598bf8c55d3aef095f958bfc3cafd79fe3fd8871/CMakeLists.txt#L50-L57

TOML Fortran is only included for the s-dftd3 binary.

**Comment by yurivict** [comment]
> That's the expected behavior, TOML Fortran is not a dependency of the s-dftd3 library.

I use ```s-dftd3``` from the external package, so it shouldn't be searched for, but it still attempts to find it:
```
-- toml-f: Trying to find installed package
-- toml-f: Installed package found
-- s-dftd3: Trying to find installed package
-- s-dftd3: Installed package found
```
IMO the order should be changed, and the conditional should be added.

**Comment by awvwgk** [comment]
DFTB+ tries to find all dependencies in the current order to avoid that subprojects can invoke their finders over the DFTB+ provided ones. However, since this is only relevant for submodule dependencies and not for external dependencies, we introduced 

https://github.com/dftbplus/dftbplus/blob/c249548c2ae2c468f13709c205997ce6f2dbdb09/CMakeLists.txt#L177-L178

Which will disable all transient dependencies, but requires to explicitly exclude the `Submodule` hybrid-dependency method.
