### ISSUE TITLE
Get rid of translational and rotational mode in modes output

### ISSUE THREAD

**Issue by chliu1990** [dftbplus/dftbplus#141]
Is that possible to let modes print only frequencies for 3N-6 vibrational modes (Just like Gaussian does, see http://gaussian.com/vib/ ). It will be useful if one wants to check whether geometry is optimized to desired minimum or saddle point on PES.

**Comment by aradi** [comment]
Currently, the modes tool prints all modes, including those belonging to translational and rotational degrees of freedom. Of course, you should see frequencies very close to zero for the non-vibrational ones.

It would be quite easy to add an option for modes, in order to omit vibrational modes with an absolute frequency below a certain tolerance. Would that do the job for you? If yes and you were interested, you may try to add it yourself and make a pull request. We can give you some guidance, if needed.

**Comment by bhourahine** [comment]
#143 should fix this. The subtraction is in the Cartesian axes, not the moments of inertia (which might be slightly more accurate).

**Comment by aradi** [comment]
The feature is now available in the development version (8ae4ae0).
