### ISSUE TITLE
RELEASE file in _build

### ISSUE THREAD

**Issue by dryndyk** [dftbplus/dftbplus#498]
I suppose that cmake does not update the _build/RELEASE file if it already exists.
Maybe it is assumed that _build should be deleted every time when updating code?

**Comment by aradi** [comment]
We have a caching behavior which I implemented to avoid calling git-commands at every rebuild during development in the legacy build framework. I think, we could safely lift it partially by automatically update the `RELEASE` file , if `cmake` is called, but keep it constant otherwise, see #499. This way, you only had to make sure, that you call `cmake` when you have updated your code, which is probably advisable anyway...
