### ISSUE TITLE
Pseudo-atom conflict with dispersion correction

### ISSUE THREAD

**Issue by galjos** [dftbplus/dftbplus#586]
Dear developers,

Currently we are performing test including pseudo-atoms in the dftb+ calculation still using the 19.1 version. We tailored specific skf-files to deal with dummy carbon atoms (labeled CX) and our initial tests proved quite positive. The overall aim of this work is to provide a QM/MM setup for carbon materials including dummy carbon atoms close to the QM/MM boundary. 

However, as soon as we invoke dispersion correction the element type CX is of course not recognised and although dftbplus terminates correctly, the associated energy and force output is broken - only some ******** are included in the output.

Is the use of dummy/pseudo atoms possible in DFTBPLUS (maybe just using a different letter such as X or Q) or, alternatively, is it possible to provide extra data in the dispersion input section for our new "element" CX?

Of course we could always turn of dispersion correction, but we believe it is inherent contribution in modern dftb applications.

Best wishes and many thanks,
Thomas S. Hofer

**Comment by awvwgk** [comment]
The dispersion corrections D3 and D4 are working with atomic numbers rather than in the species name system of DFTB+, at some point we are attempting to convert the species names to an atomic numbers. The conversion routine for both corrections will currently fail for `CX` as species name, but this kind of failure should certainly be handled more gracefully by DFTB+.

Depending on what you want to archive the D4 implementation might already provide the necessary mechanism needed for this purpose, but I haven't tested it thoroughly yet. Most (unfortunately, not all) parameters in D4 can be overwritten in the HSD input, also the conversion routine used in DFTB+ to supply D4 with atomic numbers should safely convert species names like `C*` or `C_` to the atomic number 6.
