### ISSUE TITLE
Building with Intel MPI, MKL and PLUMED

### ISSUE THREAD

**Issue by wadudmiah** [dftbplus/dftbplus#772]
Hi,

I would like to build DFTB+ with Intel MPI, MKL and PLUMED. I have read the documentation at https://github.com/dftbplus/dftbplus/blob/20.2.1/INSTALL.rst but this doesn't explain how to do this. Could you please provide the cmake configure command?

Below are the installation directories of PLUMED, ScaLAPACK and LAPACK (with the link flags):

/home/admwm1/plumed-2.7.1 (-lplumed)
${MKLROOT}/lib/intel64 (-lmkl_scalapack_ilp64 -lmkl_blacs_intelmpi_ilp64 -liomp5 -lpthread -lm -ldl)
${MKLROOT}/lib/intel64 (-lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl)

Regards,

**Comment by aradi** [comment]
Make sure `WITH_PLUMED` is set to `True`. Otherwise follow the usual compilation setup. If your compiler is recognized by CMake, it should use the `intel.cmake` config file (look at the CMake output). You can set up paths there, in case some of the libraries is not found by CMake. (Or you can adjust the `CMAKE_PREFIX_PATH` environment variable,  as described in INSTALL.rst file).
