### ISSUE TITLE
SCF parallelization with xTB Hamiltonian 

### ISSUE THREAD

**Issue by steinmig** [dftbplus/dftbplus#872]
I compiled DFTB+ from the current master with openMP support. Running an energy calculation with the xTB Hamiltonian gave me virtual identical wall times of ~2 minutes for both 1 and 32 cores. I could confirm that multiple threads (the CPU usage never reached 32, but definitely > 1) were started and also the DFTB+ output gives me a different CPU time.

Is the reason that
 - tblite does not support multiple threads for the SCF?
 - the openMP support for DFTB+ is not forwarded to tblite?
 - I am doing something wrong in the compilation?

**To Reproduce**
- Current master with gcc-9.2, all cmake defaults + `WITH_TBLITE=ON`
- Input file is attached (same as in https://github.com/dftbplus/dftbplus/issues/871)

[dftb_in.hsd.txt](https://github.com/dftbplus/dftbplus/files/7345479/dftb_in.hsd.txt)

**Comment by chemistza** [comment]
I have noticed the same thing. xTB run thrugh DFTB+ doesn't seem to scale with increasing OMP threads, whereas running the same calculation through the native tblite interface scales well.

**Comment by steinmig** [comment]
Any updates on this?

**Comment by steinmig** [comment]
I think it is worth keeping this open

**Comment by aradi** [comment]
I agree. I'll try to have a look at it. Is this also valid with the recent version of DFTB+?

**Comment by steinmig** [comment]
I'll try to test it this month

**Comment by stefanoferr** [comment]
I am experiencing this behaviour in the DFTB+ 23.1 version too.

**Comment by francescalb** [comment]
Has this been solved? I also experience problems with parallell performance when runnin xTB

**Comment by aradi** [comment]
OK. Could you just add the following lines to the input and check the system above with 1 and 2 threads? (The system is rather small). 
```
Options {
  TimingVerbosity = -1
}
```
When I do it on my laptop with the Conda version of 24.1, I see, that the diagonalization, where the program spends the most time, takes almost identical wall-clock times in both cases, that means, the matrix is too small for the diagonalization library (openblas in my case) to profit from multiple threads. If that is also the case here, you could try to use MKL instead of OpenBLAS, but otherwise there is not much we can do.
