### ISSUE TITLE
MD simulation crashes

### ISSUE THREAD

**Issue by dveclani** [dftbplus/dftbplus#898]
Dear all,

I'm a newbie user of DFTB+,

I've performed molecular dynamics simulations, the dynamics stopped after a few steps with this following error:

"/var/spool/slurm/job00041/slurm_script: line 17: 10710 Killed                  OMP_STACKSIZE=32G $BINARIO_DFTB"

I attached the files related to the calculation. 

Could you please provide me information regarding that error? 

Thank you for your time.

Best regards,
Daniele Veclani.

[FILE.zip](https://github.com/dftbplus/dftbplus/files/7616657/FILE.zip)

**Comment by aradi** [comment]
@dveclani Welcome in the community and thanks for reporting! Playing around with a gamma-only version of your example, I could reproduce the segfault. It seems to be caused by some OpenMP instructions in coordnumber.f90 (in the `get_coordination_number()`) routine, which is used by the DFTD4 dispersion. (If you remove the D4 from your input, it works without problems...)

We will try to investigate. I also ping Sebastian (@awvwgk), maybe he recognizes the problem immediately. :wink:

**Comment by dveclani** [comment]
Dear @aradi thanks for your help, I'm going to try without instruction D4. 

Thanks again.

Daniele.

**Comment by awvwgk** [comment]
Please checkout #901, which switches from the previous memory-demanding scatter-merge pattern to an atomic update pattern for the intermediary matrices. At least for the selfconsistent DFT-D4 this seems like a straight-forward solution, for the non-selfconsistent variant it will become rather ugly, unfortunately. The drawback of this solution might be a performance penalty for small thread counts, but at least we will significantly reduce the memory footprint of DFT-D4 for threaded runs.

**Comment by dveclani** [comment]
Dear @aradi and @awvwgk ,

could you provide me the procedure for the restart of the molecular dynamics simulation? 

I am unable to restart the dynamic.

Thank you for your time.

Best,
Daniele.

**Comment by aradi** [comment]
Currently, you have to copy the last velocities from the .xyz file to the `Velocities` block (make sure to set the velocities dimension in the HSD input to `AA/ps`) and use the last geometry as initial geometry. You may also read in the last charges with `ReadInitialCharges = Yes`. Sorry, this is currently still too complicated...
