### ISSUE TITLE
Incorrect masses when using TBlite.

### ISSUE THREAD

**Issue by c3091013** [dftbplus/dftbplus#940]
**Describe the bug**
Using tblite with the velocity verlet integrator to do simple MD calculations on a H/B/N/C/Fe system I found that the system tended to fly apart due to unexpectedly high velocities. Using to a simple Fe32 system I got the same problem.

Can be reproduced with this dftb_in.hsd

[dftb_in.hsd.txt](https://github.com/dftbplus/dftbplus/files/7893583/dftb_in.hsd.txt)

**Additional context**
By doing a little digging I found that the DFTB+ needs a.m.u masses when calculating accelerations from forces but the internal calculator for units DFTB+ uses when using TBlite is in au (I think theyre listed in common/atomicmass.F90) so the masses when using tblite are 3 orders or magnitude smaller than they should be. I get something closer to expected velocities and dynamics by modifying line 1497 in the dftbplus/initprogram.F90 file from: 

this%speciesMass(:) = getAtomicMass(this%speciesName)

to: 

this%speciesMass(:) = getAtomicMass(this%speciesName)*amu__au

I don't know what other features this will affect and more testing needs to be done to see if it actually fixes the issue. I'll also note that the masses are still off with the slko mass conversion ratio being 1822.776796 while amu__au=1822.888485 so the masses the slko and tblite use still are not the same.

**Comment by aradi** [comment]
Dear Izaac, thanks, that it is indeed an annoying bug, I'll fix it.

As for the difference between the masses in the SK-files and those coming from `getAtomicMass()`: That's mostly due to the fact, I guess, that in the SK-files the masses are specified typically to 2 decimal digits only, in contrast to 8 digits in `getAtomicMass()`. For back-compatibility, we will probably keep using the SK-masses for DFTB Hamiltonians and the internal ones for the xTB Hamiltonian.
