### ISSUE TITLE
dftb+ compiled and installed with mpi, How to check and run simple mpi jobs

### ISSUE THREAD

**Issue by periasamy25** [dftbplus/dftbplus#95]
dftb+ compiled with MPI (openmpi)
How to check this, using simple jobs..
Can you provide some test jobs?

**Comment by aradi** [comment]
``make test_dftb+ TESTPROC=2`` would run the test suite using 2 processes. See the ``INSTALL.rst`` file for further details.

**Comment by periasamy25** [comment]
dear aradi,

thanks for quick replay,
we are unable to be successfull on "make test_dftb+ TESTPROC=2"
see below for the error output

TEST SUMMARY
------------------------------------------------------------------------------
Match:
    None

Not run:
    non-scc/decapentaene                md/SiH-surface
    spin/Fe4                            spin/Fe4_Fermi
    spin/Fe4_commonFermi                non-scc/Si41C23N35
    spinorbit/Fe2_dual                  spinorbit/EuN
    dftb+u/Fe4                          md/ptcda-xlbomdfast
    dftb+u/Fe4_read                     spinorbit/EuN_customU
    spinorbit/Fe2                       dispersion/DNA
    non-scc/10-0Ctube_Efield            geoopt/GaAs_8_latconst
    non-scc/10-10Ctube                  md/ptcda-xlbomdfast-ldep
    non-scc/10-0Ctube                   geoopt/Vsi+O-nonscc
    spin/Fe4_noncolinear                non-scc/Si_384
    non-scc/HBDI-neutral                md/DNA
    non-scc/HBDI-cationic               md/DNA_Berendsen2
    scc/C60                             md/ptcda-xlbomd
    spinorbit/As4S4                     md/SiC64-xlbomdfast-T0
    dispersion/DNA-damped               md/SiC64-xlbomdfast
    md/ice_Ic                           non-scc/Si_216
    scc/C60_Fermi                       md/ptcda-xlbomd-ldep
    scc/10-0Ctube-extfield              geoopt/Vsi+O
    scc/SiC_64                          scc/SiC64+V_dynforce
------------------------------------------------------------------------------
Status: FAIL
------------------------------------------------------------------------------
Details in:
    _autotest/stderror.log
    _autotest/tagdiff.log
==============================================================================
make[1]: *** [test] Error 1
make[1]: Leaving directory `/opt/apps/dftbplus-master/_build/prog/dftb+'
make: *** [test_dftb+] Error 2
[root@dirac dftbplus-master]#

**Comment by periasamy25** [comment]
The stderror.log and tagdiff.log are empty no info found in those files.

**Comment by periasamy25** [comment]
Can you please help on these??

**Comment by bhourahine** [comment]
If 
  make dftb+
completed without an error, then some possibilities to check are

1. Missing Slater-Koster files for the tests
  ls external/slakos/origin/
if the utils/get_opt_externals script ran correctly you should see from the top directory of the project

$ ls external/slakos/origin/
hyb-0-2  mio-1-1  pbc-0-3  rare-0-2  README.rst

2. There is a problem with your mpi set up or the compilation of the binary. What happens if after the make test_dftb+ fails you then manually run one of the test examples:

cd _build/prog/dftb+/_autotest/non-scc/Si41C23N35
mpirun -np 2 ../../../dftb+

or 

mpiexec -n 2 ../../../dftb+

?

**Comment by periasamy25** [comment]
I was compiled dftb+ with gcc : 4.9.4. I got the following error.. But make completed. after that **make test** failed..

mpifx_helper.f90:18.6:

  use mpi
      1
Fatal Error: Cannot read module file 'mpi.mod' opened at (1), ## **because it was created by a different version of GNU Fortran**
make[2]: *** [mpifx_helper.o] Error 1
rm mpifx_allreduce.f90 mpifx_bcast.f90 mpifx_finalize.f90 mpifx_helper.f90 mpifx_allgather.f90 mpifx_send.f90 mpifx_barrier.f90 mpifx_init.f90 mpifx_scatter.f90 mpifx_gather.f90 mpifx_constants.f90 mpifx_recv.f90 mpifx_get_processor_name.f90 mpifx_reduce.f90 mpifx_comm.f90 mpifx_common.f90 libmpifx.f90 mpifx_abort.f90
make[2]: Leaving directory `/opt/apps/dftbplus-master/_build/external/mpifx'
make[1]: *** [libmpifx] Error 2
make[1]: Leaving directory `/opt/apps/dftbplus-master/_build/external/mpifx'
make: *** [external_mpifx] Error 2

**Comment by bhourahine** [comment]
OK, so the compilation failed due to a problem with your system's mpi set up. You will need to work out what is installed (there is not enough detail here to do that). 

Do you need to use distributed memory parallelism, since compiling without MPI would bypass this problem. The resulting code is still parallel on shared memory platforms (particularly with  thread aware BLAS).

**Comment by periasamy25** [comment]
we are having gcc 4.9.4, gfortran 4.9.4 and openmpi-3.0.0 in our environment. 
Can you help me to configure Distributed memory parallelism in our cluster? 
Please provide the requirements, configuration and testing procedures..

**Comment by aradi** [comment]
We do not support gcc/gfortran 4.9.4, you must have at least gfortran 5.4 to compile DFTB+. Otherwise please have a detailed look at `INSTALL.rst` for general information about configuring installing and testing DFTB+. If you have a DFTB+ specific question, we can try to answer. However, it would be very advisable to ask your local system administrators help, if you are unexperienced with compiling MPI-parallel codes.

**Comment by EnderAraujo** [comment]
Greetings.

I follow the instructions for the installation, but when executing the "make test" I have the following errors:
dftbplus/prog/dftb+/make.build:76:
make[1]: *** [test] Error 1

dftbplus /_build/prog/dftb+ makefile:92
make: *** [test_dftb+] Error 2

**Comment by aradi** [comment]
Dear Ender,

> I follow the instructions for the installation, but when executing the
> "make test" I have the following errors:
> dftbplus/prog/dftb+/make.build:76:
> make[1]: *** [test] Error 1
> 
> dftbplus /_build/prog/dftb+ makefile:92
> make: *** [test_dftb+] Error 2

Well, it is basically impossible to tell, what your error is.

But, could you, before running the test suite, test for a simple example
manually, if the dftb+ binary you use works well?

  Best regards,

  Bálint


-- 
Dr. Bálint Aradi
Bremen Center for Computational Materials Science, University of Bremen
http://www.bccms.uni-bremen.de/cms/people/b-aradi/
